spring:
  application:
    name: nextflat
  
  datasource:
    url: jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:5432/postgres?sslmode=require
    username: postgres.eqevklmjawzcrifessom
    password: eTVYfFAD884rwhas
    driver-class-name: org.postgresql.Driver

    hikari:
      max-lifetime: 120000
      idle-timeout: 60000
      keepalive-time: 30000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false

server:
  port: 8080