spring:
  application:
    name: nextflat

  # Configuración de la Base de Datos (Supabase / PostgreSQL)
  datasource:
    url: jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:5432/postgres
    username: postgres.rxpgzthbvgjbkatalyly
    password: LaContraseñaMasSeguraDelMundo1234567890.
    driver-class-name: org.postgresql.Driver
    # Configuración para evitar cortes de conexión con Supabase
    hikari:
      max-lifetime: 120000 # Destruye las conexiones cada 2 minutos antes de que Supabase lo haga
      idle-timeout: 60000 # Limpia las conexiones inactivas al minuto
      keepalive-time: 30000 # Envía un "latido" cada 30 segundos para mantenerla viva

  # Configuración de Hibernate / JPA
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false

server:
  port: 8080
